"""Scribpy public package interface."""

__version__ = "0.1.0"

from scribpy.core import (
    CollectionDiagnostic,
    CollectionDiagnosticReport,
    CollectionDiagnosticRule,
    DiagnosticSeverity,
    ExternalImageReferenceRule,
    FolderManifest,
    HeadingLevelOverflowRule,
    InternalMarkdownLinkRule,
    LocalImageMissingRule,
    MarkdownCollection,
    MarkdownDocument,
    MarkdownFile,
    MarkdownImageReference,
    OutlineNode,
    RootManifest,
    SourceFirstHeadingH1Rule,
    SourceH1CountRule,
    init_from_outline,
    init_skeleton,
    parse_outline,
)
from scribpy.errors import (
    InvalidMarkdownError,
    InvalidScribpyManifestError,
    OutlineValidationError,
    ScaffoldCollisionError,
    ScribpyError,
    ScribpyManifestWarning,
)
from scribpy.log import logging_context

__all__ = [
    "CollectionDiagnostic",
    "CollectionDiagnosticReport",
    "CollectionDiagnosticRule",
    "DiagnosticSeverity",
    "ExternalImageReferenceRule",
    "FolderManifest",
    "HeadingLevelOverflowRule",
    "InternalMarkdownLinkRule",
    "InvalidMarkdownError",
    "InvalidScribpyManifestError",
    "LocalImageMissingRule",
    "MarkdownCollection",
    "MarkdownDocument",
    "MarkdownFile",
    "MarkdownImageReference",
    "OutlineNode",
    "OutlineValidationError",
    "RootManifest",
    "ScaffoldCollisionError",
    "ScribpyError",
    "ScribpyManifestWarning",
    "SourceFirstHeadingH1Rule",
    "SourceH1CountRule",
    "init_from_outline",
    "init_skeleton",
    "logging_context",
    "parse_outline",
]
