"""Scribpy public package interface."""

__version__ = "0.1.0"

from scribpy.core import (
    CollectionDiagnostic,
    CollectionDiagnosticReport,
    CollectionDiagnosticRule,
    DiagnosticSeverity,
    ExternalImageReferenceRule,
    FolderManifest,
    HeadingLevelOverflowRule,
    InternalMarkdownLinkRule,
    LocalImageMissingRule,
    MarkdownCollection,
    MarkdownDocument,
    MarkdownFile,
    MarkdownImageReference,
    OutlineNode,
    ProjectDiagnostic,
    ProjectValidationReport,
    RootManifest,
    SourceFirstHeadingH1Rule,
    SourceH1CountRule,
    html_export,
    init_from_outline,
    init_skeleton,
    mkdocs_export,
    parse_outline,
    validate_project,
)
from scribpy.errors import (
    InvalidMarkdownError,
    InvalidScribpyManifestError,
    OutlineValidationError,
    ScaffoldCollisionError,
    ScribpyError,
    ScribpyManifestWarning,
)
from scribpy.log import logging_context
from scribpy.presentation import render_validation_report
from scribpy.validation import valid_report

__all__ = [
    "CollectionDiagnostic",
    "CollectionDiagnosticReport",
    "CollectionDiagnosticRule",
    "DiagnosticSeverity",
    "ExternalImageReferenceRule",
    "FolderManifest",
    "HeadingLevelOverflowRule",
    "InternalMarkdownLinkRule",
    "InvalidMarkdownError",
    "InvalidScribpyManifestError",
    "LocalImageMissingRule",
    "MarkdownCollection",
    "MarkdownDocument",
    "MarkdownFile",
    "MarkdownImageReference",
    "OutlineNode",
    "OutlineValidationError",
    "ProjectDiagnostic",
    "ProjectValidationReport",
    "RootManifest",
    "ScaffoldCollisionError",
    "ScribpyError",
    "ScribpyManifestWarning",
    "SourceFirstHeadingH1Rule",
    "SourceH1CountRule",
    "html_export",
    "init_from_outline",
    "init_skeleton",
    "logging_context",
    "mkdocs_export",
    "parse_outline",
    "render_validation_report",
    "valid_report",
    "validate_project",
]
