"""Demo project creation service."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from scribpy.model import Diagnostic, LintResult
from scribpy.utils import has_errors

DemoVariant = Literal["valid", "invalid"]

_VALID_DEMO_FILES: dict[Path, str] = {
    Path("scribpy.toml"): """[project]
name = "scribpy-demo"

[paths]
source = "doc"

[index]
mode = "explicit"
files = [
  "index.md",
  "guide/setup.md",
]
""",
    Path("doc/index.md"): """# Scribpy Demo

This is the first document in the explicit index.

Use this project to try the phase 2 project-context chain:

```bash
scribpy index check --root .
```
""",
    Path("doc/guide/setup.md"): """# Setup

This is the second document in the explicit index.

The configured order is controlled by `scribpy.toml`.
""",
    Path("README.md"): """# Scribpy Valid Demo Project

This project was generated by:

```bash
scribpy demo create
```

Try the index check:

```bash
scribpy index check --root .
```
""",
}

_INVALID_DEMO_FILES: dict[Path, str] = {
    Path("scribpy.toml"): """[project]
name = "scribpy-invalid-demo"

[paths]
source = "doc"

[index]
mode = "explicit"
files = [
  "index.md",
  "missing.md",
  "index.md",
]
""",
    Path("doc/index.md"): """# Scribpy Invalid Demo

This project is intentionally invalid.

The explicit index in `scribpy.toml` references `missing.md` and repeats
`index.md`, so `scribpy index check --root .` should report diagnostics.
""",
    Path("doc/guide/setup.md"): """# Setup

This file exists but is not listed in the explicit index.

It demonstrates the `IDX005` warning.
""",
    Path("README.md"): """# Scribpy Invalid Demo Project

This project was generated by:

```bash
scribpy demo create --variant invalid
```

Try the index check:

```bash
scribpy index check --root .
```

Expected diagnostics:

- `IDX002`: `missing.md` is listed but does not exist;
- `IDX003`: `index.md` is listed twice;
- `IDX005`: `guide/setup.md` exists but is not listed.
""",
}

_DEMO_FILES_BY_VARIANT: dict[DemoVariant, dict[Path, str]] = {
    "valid": _VALID_DEMO_FILES,
    "invalid": _INVALID_DEMO_FILES,
}


def create_demo_project(
    target: Path,
    *,
    force: bool = False,
    variant: DemoVariant = "valid",
) -> LintResult:
    """Create a small external Scribpy tutorial project.

    Args:
        target: Directory where the demo project should be created.
        force: When true, overwrite files managed by the demo template.
        variant: Demo template variant. ``"valid"`` creates a project that
            passes ``scribpy index check``; ``"invalid"`` creates a project
            with intentional index diagnostics for tutorial purposes.

    Returns:
        Lint-style result containing user-facing diagnostics. A successful
        creation returns no diagnostics.
    """
    files = _DEMO_FILES_BY_VARIANT[variant]
    diagnostics = _validate_target(target, files=files, force=force)
    if has_errors(diagnostics):
        return LintResult(diagnostics=diagnostics, failed=True)

    try:
        for relative_path, content in files.items():
            path = target / relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    except OSError as error:
        diagnostics = (
            Diagnostic(
                severity="error",
                code="DEMO002",
                message=f"Could not create demo project: {error}",
                path=target,
            ),
        )

    return LintResult(diagnostics=diagnostics, failed=has_errors(diagnostics))


def _validate_target(
    target: Path,
    *,
    files: dict[Path, str],
    force: bool,
) -> tuple[Diagnostic, ...]:
    if target.exists() and not target.is_dir():
        return (
            Diagnostic(
                severity="error",
                code="DEMO001",
                message="Demo target exists and is not a directory.",
                path=target,
                hint="Choose a directory path or remove the existing file.",
            ),
        )

    if force:
        return ()

    existing_files = tuple(
        path for path in _planned_paths(target, files=files) if path.exists()
    )
    return tuple(
        Diagnostic(
            severity="error",
            code="DEMO001",
            message="Demo file already exists.",
            path=path,
            hint=(
                "Choose an empty target directory or pass --force to overwrite "
                "demo files."
            ),
        )
        for path in existing_files
    )


def _planned_paths(target: Path, *, files: dict[Path, str]) -> tuple[Path, ...]:
    return tuple(target / relative_path for relative_path in files)


__all__ = ["DemoVariant", "create_demo_project"]
