"""Demo project creation service."""

from __future__ import annotations

from pathlib import Path

from scribpy.model import Diagnostic, LintResult
from scribpy.utils import has_errors

_DEMO_FILES: dict[Path, str] = {
    Path("scribpy.toml"): """[project]
name = "scribpy-demo"

[paths]
source = "doc"

[index]
mode = "explicit"
files = [
  "index.md",
  "guide/setup.md",
]
""",
    Path("doc/index.md"): """# Scribpy Demo

This is the first document in the explicit index.

Use this project to try the phase 2 project-context chain:

```bash
scribpy index check --root .
```
""",
    Path("doc/guide/setup.md"): """# Setup

This is the second document in the explicit index.

The configured order is controlled by `scribpy.toml`.
""",
    Path("README.md"): """# Scribpy Demo Project

This project was generated by:

```bash
scribpy demo create
```

Try the index check:

```bash
scribpy index check --root .
```
""",
}


def create_demo_project(target: Path, *, force: bool = False) -> LintResult:
    """Create a small external Scribpy tutorial project.

    Args:
        target: Directory where the demo project should be created.
        force: When true, overwrite files managed by the demo template.

    Returns:
        Lint-style result containing user-facing diagnostics. A successful
        creation returns no diagnostics.
    """
    diagnostics = _validate_target(target, force=force)
    if has_errors(diagnostics):
        return LintResult(diagnostics=diagnostics, failed=True)

    try:
        for relative_path, content in _DEMO_FILES.items():
            path = target / relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    except OSError as error:
        diagnostics = (
            Diagnostic(
                severity="error",
                code="DEMO002",
                message=f"Could not create demo project: {error}",
                path=target,
            ),
        )

    return LintResult(diagnostics=diagnostics, failed=has_errors(diagnostics))


def _validate_target(target: Path, *, force: bool) -> tuple[Diagnostic, ...]:
    if target.exists() and not target.is_dir():
        return (
            Diagnostic(
                severity="error",
                code="DEMO001",
                message="Demo target exists and is not a directory.",
                path=target,
                hint="Choose a directory path or remove the existing file.",
            ),
        )

    if force:
        return ()

    existing_files = tuple(path for path in _planned_paths(target) if path.exists())
    return tuple(
        Diagnostic(
            severity="error",
            code="DEMO001",
            message="Demo file already exists.",
            path=path,
            hint=(
                "Choose an empty target directory or pass --force to overwrite "
                "demo files."
            ),
        )
        for path in existing_files
    )


def _planned_paths(target: Path) -> tuple[Path, ...]:
    return tuple(target / relative_path for relative_path in _DEMO_FILES)


__all__ = ["create_demo_project"]
