"""README content for the generated valid demo project."""

from __future__ import annotations

VALID_DEMO_README = """\
# Scribpy Demo Project

Generated by:

```bash
scribpy demo create
```

The generated manual contains 33 Markdown documents under `doc/`, arranged in a
nested tree that exercises explicit indexing, link resolution, transforms,
assembled Markdown builds, offline PlantUML rendering, single-page HTML output,
and MkDocs-backed site generation.

## End-to-end walkthrough

Run the commands below from this demo directory, in order. They mirror the
normal Scribpy workflow: validate the project, inspect semantics, lint content,
then build the publication targets.

## Phase 2 — Project context

```bash
scribpy index check --root .
```

## Phase 3 — Parse and semantic extraction

```bash
scribpy parse check --root .
```

## Phase 4 — Lint-first user value

```bash
scribpy lint --root .
```

## Phases 5–6 — Markdown build and transforms

```bash
scribpy build markdown --root .
```

This writes:

```text
build/markdown/document.md
```

## Phase 7 — HTML outputs

Build the portable single-page document:

```bash
scribpy build html --mode single-page --root .
```

The demo contains complex PlantUML diagrams rendered locally into SVG assets.
Install a Java runtime before running the HTML builds so Scribpy can execute its
bundled PlantUML engine without using any external service.

Inspect:

```text
build/html/index.html
build/html/css/demo.css
build/html/assets/
```

Then build the multi-page documentation site:

```bash
scribpy build html --mode site --root .
```

Scribpy prepares the MkDocs inputs and wraps `mkdocs build` itself. Inspect:

```text
build/site/mkdocs.yml
build/site/docs/
build/site/site/index.html
```

Use `single-page` when you need one distributable document. Use `site` when you
need a browsable multi-page documentation website.

The demo `scribpy.toml` configures the assembled document title, generated table
of contents, TOC depth, and section-numbering style:

```toml
[document]
title = "Scribpy Demo Manual"

[document.toc]
enabled = true
max_level = 3
style = "bullet"

[document.numbering]
enabled = true
max_level = 3
style = "decimal"

[builders.html]
mode = "single-page"
css_files = ["theme/demo.css"]
theme = "readthedocs"
```

## Next steps

1. Edit one or two files under `doc/`.
2. Re-run the quality gates:

   ```bash
   scribpy index check --root .
   scribpy parse check --root .
   scribpy lint --root .
   ```

3. Rebuild the publication targets:

   ```bash
   scribpy build markdown --root .
   scribpy build html --mode single-page --root .
   scribpy build html --mode site --root .
   ```

4. Compare `build/markdown/document.md`, `build/html/index.html`, and
   `build/site/site/index.html` to see how the same corpus is published in each
   format.

The configured site theme is `readthedocs`; change `builders.html.theme` to try
another MkDocs theme.

## Execution logs

Enable execution logs when you want to inspect the chain without changing the
diagnostics policy:

```bash
scribpy --log-level INFO build html --mode site --root .
```

By default, the log file is written to:

```text
build/logs/scribpy.log
```

Use a custom path or mirror logs to the console when needed:

```bash
scribpy --log-level DEBUG --log-console --log-file logs/demo.log lint --root .
```

The Python API exposes the same capability:

```python
import scribpy

with scribpy.logging_context(level="INFO"):
    scribpy.build_html(".", mode="site")
```
"""

__all__ = ["VALID_DEMO_README"]
