"""Demo project creation service."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

from scribpy.model import Diagnostic, LintResult
from scribpy.utils import has_errors

DemoVariant = Literal["valid", "invalid"]

_VALID_DEMO_FILES: dict[Path, str] = {
    Path("scribpy.toml"): """\
[project]
name = "scribpy-demo"

[paths]
source = "doc"

[index]
mode = "explicit"
files = [
  "index.md",
  "guide/setup.md",
]
""",
    Path("doc/index.md"): """\
---
title: Scribpy Demo
author: Demo Author
version: 1
tags:
  - scribpy
  - docs-as-code
---

# Scribpy Demo

Welcome to the Scribpy demo project.

This document exercises the **phase 3 parsing chain**: frontmatter extraction,
heading detection, link extraction, and image references.

## What Scribpy Does

Scribpy converts Markdown sources into structured output formats.
See the [setup guide](guide/setup.md) for the next steps.

Visit the [Scribpy project](https://github.com/example/scribpy) for more
information.

## Project Structure

The document index is declared in `scribpy.toml`.
Order is explicit: `index.md` is parsed before `guide/setup.md`.

![Scribpy architecture overview](assets/architecture.png)
""",
    Path("doc/guide/setup.md"): """\
---
title: Setup Guide
author: Demo Author
draft: false
---

# Setup Guide

This is the second document in the explicit index.

## Prerequisites

Before you start, make sure you have Python 3.12 or later installed.
See the [index](../index.md) for the project overview.

## Installation

Install Scribpy with pip:

```bash
pip install scribpy
```

## Verification

Run the full chain check to verify parsing works:

```bash
scribpy parse check --root .
```

![Setup diagram](assets/setup.png)
""",
    Path("README.md"): """\
# Scribpy Demo Project

Generated by:

```bash
scribpy demo create
```

## Phase 2 — Project context

```bash
scribpy index check --root .
```

Validates configuration, source discovery, and document index.

## Phase 3 — Parse and semantic extraction

```bash
scribpy parse check --root .
```

Parses every Markdown file and extracts frontmatter, headings, links,
and image references. Reports diagnostics for any file that cannot be read
or parsed.

## Next steps

Re-run checks after editing `doc/index.md` or `doc/guide/setup.md`
and observe how diagnostics change.
""",
}

_INVALID_DEMO_FILES: dict[Path, str] = {
    Path("scribpy.toml"): """\
[project]
name = "scribpy-invalid-demo"

[paths]
source = "doc"

[index]
mode = "explicit"
files = [
  "index.md",
  "missing.md",
  "index.md",
]
""",
    Path("doc/index.md"): """\
---
title: Scribpy Invalid Demo
author: Demo Author
---

# Scribpy Invalid Demo

This project is **intentionally invalid** to demonstrate Scribpy diagnostics.

The explicit index in `scribpy.toml` references `missing.md` and repeats
`index.md`. Run the checks below to see the expected errors.

See [setup](guide/setup.md) — this file exists but is excluded from the index.

![Demo image](assets/demo.png)
""",
    Path("doc/guide/setup.md"): """\
---
title: Setup (unlisted)
---

# Setup

This file exists but is not listed in the explicit index.

It demonstrates the `IDX005` warning: Scribpy found the file during source
discovery but it is absent from `index.files`.

## Links

Back to [index](../index.md).
""",
    Path("README.md"): """\
# Scribpy Invalid Demo Project

Generated by:

```bash
scribpy demo create --variant invalid
```

## Phase 2 — Project context

```bash
scribpy index check --root .
```

Expected diagnostics:

- `IDX002`: `missing.md` is listed but does not exist
- `IDX003`: `index.md` is listed twice
- `IDX005`: `guide/setup.md` exists but is not listed

## Phase 3 — Parse and semantic extraction

```bash
scribpy parse check --root .
```

Because the index is broken, `parse check` will also fail.
Fix the index first, then rerun to see a clean parse result.
""",
}

_DEMO_FILES_BY_VARIANT: dict[DemoVariant, dict[Path, str]] = {
    "valid": _VALID_DEMO_FILES,
    "invalid": _INVALID_DEMO_FILES,
}


def create_demo_project(
    target: Path,
    *,
    force: bool = False,
    variant: DemoVariant = "valid",
) -> LintResult:
    """Create a small external Scribpy tutorial project.

    Args:
        target: Directory where the demo project should be created.
        force: When true, overwrite files managed by the demo template.
        variant: Demo template variant. ``"valid"`` creates a project that
            passes ``scribpy index check``; ``"invalid"`` creates a project
            with intentional index diagnostics for tutorial purposes.

    Returns:
        Lint-style result containing user-facing diagnostics. A successful
        creation returns no diagnostics.
    """
    files = _DEMO_FILES_BY_VARIANT[variant]
    diagnostics = _validate_target(target, files=files, force=force)
    if has_errors(diagnostics):
        return LintResult(diagnostics=diagnostics, failed=True)

    try:
        for relative_path, content in files.items():
            path = target / relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    except OSError as error:
        diagnostics = (
            Diagnostic(
                severity="error",
                code="DEMO002",
                message=f"Could not create demo project: {error}",
                path=target,
            ),
        )

    return LintResult(diagnostics=diagnostics, failed=has_errors(diagnostics))


def _validate_target(
    target: Path,
    *,
    files: dict[Path, str],
    force: bool,
) -> tuple[Diagnostic, ...]:
    if target.exists() and not target.is_dir():
        return (
            Diagnostic(
                severity="error",
                code="DEMO001",
                message="Demo target exists and is not a directory.",
                path=target,
                hint="Choose a directory path or remove the existing file.",
            ),
        )

    if force:
        return ()

    existing_files = tuple(
        path for path in _planned_paths(target, files=files) if path.exists()
    )
    return tuple(
        Diagnostic(
            severity="error",
            code="DEMO001",
            message="Demo file already exists.",
            path=path,
            hint=(
                "Choose an empty target directory or pass --force to overwrite "
                "demo files."
            ),
        )
        for path in existing_files
    )


def _planned_paths(target: Path, *, files: dict[Path, str]) -> tuple[Path, ...]:
    return tuple(target / relative_path for relative_path in files)


__all__ = ["DemoVariant", "create_demo_project"]
